version: "3.7"
services:
  db:
    image: mariadb:latest
    volumes:
      - .:/data
    ports:
    - 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: default
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  pma:
    image: phpmyadmin:latest
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
    - 8080:80
